# Generated by Django 3.0.4 on 2020-05-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0002_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DONE', 'DONE')], default='ACTIVE', max_length=255),
        ),
    ]
