# Generated by Django 3.0.4 on 2020-05-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(default='PPA', max_length=255),
        ),
    ]
