# Generated by Django 3.0.6 on 2020-05-21 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0008_correction_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='theme',
            name='jury',
            field=models.CharField(choices=[('ENEM', 'ENEM'), ('CESPE', 'CESPE'), ('VUNESP', 'VUNESP')], max_length=255),
        ),
        migrations.CreateModel(
            name='CorrectionItemComment',
            fields=[
                ('correctionitemtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='essay_manager.CorrectionItemType')),
                ('x0', models.IntegerField()),
                ('y0', models.IntegerField()),
                ('count', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('RED', 'RED'), ('PURPLE', 'PURPLE'), ('GREY', 'GREY'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW')], max_length=255)),
            ],
            bases=('essay_manager.correctionitemtype',),
        ),
        migrations.CreateModel(
            name='CorrectionItemLine',
            fields=[
                ('correctionitemtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='essay_manager.CorrectionItemType')),
                ('x0', models.IntegerField()),
                ('y0', models.IntegerField()),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('color', models.CharField(choices=[('RED', 'RED'), ('PURPLE', 'PURPLE'), ('GREY', 'GREY'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW')], max_length=255)),
                ('pen_size', models.IntegerField(default=25)),
            ],
            bases=('essay_manager.correctionitemtype',),
        ),
        migrations.CreateModel(
            name='CorrectionItemRectangle',
            fields=[
                ('correctionitemtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='essay_manager.CorrectionItemType')),
                ('x0', models.IntegerField()),
                ('y0', models.IntegerField()),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('color', models.CharField(choices=[('RED', 'RED'), ('PURPLE', 'PURPLE'), ('GREY', 'GREY'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW')], max_length=255)),
            ],
            bases=('essay_manager.correctionitemtype',),
        ),
        migrations.CreateModel(
            name='CorrectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essay_manager.Correction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essay_manager.CorrectionItemType')),
            ],
        ),
    ]
