# Generated by Django 3.0.6 on 2020-05-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0009_auto_20200521_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctionitemcomment',
            name='correctionitemtype_ptr',
        ),
        migrations.RemoveField(
            model_name='correctionitemline',
            name='correctionitemtype_ptr',
        ),
        migrations.RemoveField(
            model_name='correctionitemrectangle',
            name='correctionitemtype_ptr',
        ),
        migrations.AddField(
            model_name='correction',
            name='data',
            field=models.CharField(default='{}', max_length=255),
        ),
        migrations.DeleteModel(
            name='CorrectionItem',
        ),
        migrations.DeleteModel(
            name='CorrectionItemComment',
        ),
        migrations.DeleteModel(
            name='CorrectionItemLine',
        ),
        migrations.DeleteModel(
            name='CorrectionItemRectangle',
        ),
        migrations.DeleteModel(
            name='CorrectionItemType',
        ),
    ]
