# Generated by Django 3.0.6 on 2020-05-31 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0011_auto_20200528_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('competency', models.CharField(choices=[('C1', 'Competência 1'), ('C2', 'Competência 2'), ('C3', 'Competência 3'), ('C4', 'Competência 4'), ('C5', 'Competência 5')], default='c1', max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essay_manager.ErrorClassification')),
            ],
        ),
    ]
