# Generated by Django 3.0.6 on 2020-05-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0013_auto_20200531_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorclassification',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='errorclassification',
            name='competency',
            field=models.CharField(choices=[('1', 'Competência 1'), ('2', 'Competência 2'), ('3', 'Competência 3'), ('4', 'Competência 4'), ('5', 'Competência 5')], default='1', max_length=255),
        ),
    ]
