# Generated by Django 3.0.6 on 2020-05-31 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0014_auto_20200531_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorclassification',
            name='has_children',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='errorclassification',
            name='p_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_parent', to='essay_manager.ErrorClassification'),
        ),
    ]
