# Generated by Django 3.0.6 on 2020-05-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0015_auto_20200531_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorclassification',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
