# Generated by Django 3.0.6 on 2020-06-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0016_errorclassification_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorclassification',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
