# Generated by Django 3.0.6 on 2020-06-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0017_errorclassification_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorclassification',
            name='apply_on_select',
            field=models.BooleanField(default=False),
        ),
    ]
