# Generated by Django 3.0.6 on 2020-06-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0018_errorclassification_apply_on_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorclassification',
            name='target',
            field=models.CharField(default='comment-text', max_length=255),
        ),
    ]
