# Generated by Django 3.0.6 on 2020-06-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0019_errorclassification_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='type',
            field=models.CharField(choices=[('FREE', 'FREE'), ('PAID', 'PAID')], default='FREE', max_length=255),
        ),
    ]
