# Generated by Django 3.0.6 on 2020-06-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0020_theme_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='mailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='theme',
            name='type',
            field=models.CharField(choices=[('FREE', 'SOLIDÁRIO'), ('PAID', 'PAGO')], default='PAID', max_length=255),
        ),
    ]
