# Generated by Django 3.0.4 on 2020-06-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0021_auto_20200622_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
