# Generated by Django 3.0.4 on 2020-06-29 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0022_auto_20200623_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='nullified',
            field=models.BooleanField(default=False, verbose_name='redação anulada'),
        ),
        migrations.AlterField(
            model_name='errorclassification',
            name='competency',
            field=models.CharField(choices=[('1', 'Competência 1'), ('2', 'Competência 2'), ('3', 'Competência 3'), ('4', 'Competência 4'), ('5', 'Competência 5'), ('0', 'Nota 0')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='errorclassification',
            name='p_parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_parent', to='essay_manager.ErrorClassification'),
        ),
    ]
