# Generated by Django 3.0.3 on 2020-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0023_auto_20200629_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorclassification',
            name='description',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
