# Generated by Django 3.0.4 on 2020-07-06 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0024_auto_20200701_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='correction',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='correction',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
