# Generated by Django 3.0.4 on 2020-07-06 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0025_auto_20200706_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correction',
            options={'verbose_name': 'correção', 'verbose_name_plural': 'correções'},
        ),
        migrations.AlterModelOptions(
            name='errorclassification',
            options={'verbose_name': 'erro pontual', 'verbose_name_plural': 'erros pontuais'},
        ),
        migrations.AlterModelOptions(
            name='essay',
            options={'verbose_name': 'Redação', 'verbose_name_plural': 'Redações'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'tema', 'verbose_name_plural': 'temas'},
        ),
        migrations.RemoveField(
            model_name='errorclassification',
            name='apply_on_select',
        ),
        migrations.CreateModel(
            name='GenericErrorClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1023, null=True)),
                ('competency', models.CharField(choices=[('1', 'Competência 1'), ('2', 'Competência 2'), ('3', 'Competência 3'), ('4', 'Competência 4'), ('5', 'Competência 5'), ('0', 'Nota 0')], default='1', max_length=255)),
                ('has_children', models.BooleanField(default=False, editable=False)),
                ('weight', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('apply_on_select', models.BooleanField(default=False)),
                ('target', models.CharField(default='formTextareac1', max_length=255)),
                ('p_parent', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gec_previous_parent', to='essay_manager.GenericErrorClassification')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essay_manager.GenericErrorClassification')),
            ],
            options={
                'verbose_name': 'erro de competência',
                'verbose_name_plural': 'erros de competência',
            },
        ),
    ]
