# Generated by Django 3.0.4 on 2020-07-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0026_auto_20200706_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='auxilliary_text',
        ),
        migrations.AddField(
            model_name='theme',
            name='file',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correction',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='correction',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
