# Generated by Django 3.0.4 on 2020-07-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0027_auto_20200716_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='nullified',
            field=models.BooleanField(default=False),
        ),
    ]
