# Generated by Django 3.0.4 on 2020-07-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0028_essay_nullified'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='axis',
            field=models.CharField(choices=[('HEALTH', 'Saúde'), ('EDUCATION', 'Educação'), ('POLITICS', 'Política'), ('ECONOMICS', 'Economia'), ('SOCIAL', 'Social'), ('ENVIRONMENT', 'Meio Ambiente'), ('TECHNOLOGY', 'Tecnologia'), ('OTHER', 'Outros eixos'), ('EXTERNAL', 'De outros alunos')], default='OTHER', max_length=255),
        ),
    ]
