# Generated by Django 3.0.4 on 2020-07-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0030_theme_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_grade',
            field=models.IntegerField(blank=True, choices=[(800, 800), (900, 900), (1000, 1000)], null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='axis',
            field=models.CharField(choices=[('Saúde', 'Saúde'), ('Educação', 'Educação'), ('Política', 'Política'), ('Economia', 'Economia'), ('Social', 'Social'), ('Meio Ambiente', 'Meio Ambiente'), ('Tecnologia', 'Tecnologia'), ('Outros eixos', 'Outros eixos'), ('De outros alunos', 'De outros alunos')], default='OTHER', max_length=255),
        ),
    ]
