# Generated by Django 3.0.4 on 2020-08-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0031_auto_20200730_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='production',
            field=models.CharField(blank=True, choices=[('2 por mês', '2 por mês'), ('1 por semana', '1 por semana'), ('2 por semana', '2 por semana'), ('3 por semana', '3 por semana')], max_length=255, null=True),
        ),
    ]
