# Generated by Django 3.0.3 on 2020-08-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0033_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'evento', 'verbose_name_plural': 'eventos'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfis'},
        ),
    ]
