# Generated by Django 3.0.8 on 2020-08-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0034_auto_20200801_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='highlighted_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='highlighted_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
