# Generated by Django 3.0.8 on 2020-08-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0035_auto_20200808_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'exercício',
                'verbose_name_plural': 'exercícios',
            },
        ),
        migrations.AlterField(
            model_name='theme',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Visível'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='axis',
            field=models.CharField(choices=[('Saúde', 'Saúde'), ('Educação', 'Educação'), ('Política e Economia', 'Política e Economia'), ('Organização Social', 'Organização Social'), ('Meio Ambiente', 'Meio Ambiente'), ('Tecnologia', 'Tecnologia'), ('Outros Eixos', 'Outros Eixos'), ('De Outros Alunos', 'De Outros Alunos')], default='OTHER', max_length=255, verbose_name='Eixo'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='end_date',
            field=models.DateTimeField(verbose_name='Data de término'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Arquivo descritivo'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='highlighted_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de término'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='highlighted_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='jury',
            field=models.CharField(choices=[('ENEM', 'ENEM'), ('CESPE', 'CESPE'), ('VUNESP', 'VUNESP')], max_length=255, verbose_name='Banca'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='start_date',
            field=models.DateTimeField(verbose_name='Data de iníncio'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='type',
            field=models.CharField(choices=[('FREE', 'SOLIDÁRIO'), ('PAID', 'PAGO')], default='PAID', max_length=255, verbose_name='Disponibilidade'),
        ),
    ]
