# Generated by Django 3.0.8 on 2020-08-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0036_auto_20200809_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciselist',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
