# Generated by Django 3.0.8 on 2020-08-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0038_completedexerciselist_interestedexerciselist'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedexerciselist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interestedexerciselist',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CompletedExerciseList',
        ),
    ]
