# Generated by Django 3.0.8 on 2020-08-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0039_auto_20200809_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='mode',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=255),
        ),
    ]
