# Generated by Django 3.0.8 on 2020-08-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0041_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_production',
            field=models.IntegerField(blank=True, choices=[('2 por mês', '2 por mês'), ('1 por semana', '1 por semana'), ('2 por semana', '2 por semana'), ('3 por semana', '3 por semana')], null=True),
        ),
    ]
