# Generated by Django 3.0.8 on 2020-08-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0042_profile_target_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='production',
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_production',
            field=models.CharField(blank=True, choices=[('2 por mês', '2 por mês'), ('1 por semana', '1 por semana'), ('2 por semana', '2 por semana'), ('3 por semana', '3 por semana')], max_length=255, null=True),
        ),
    ]
