# Generated by Django 3.0.8 on 2020-08-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0044_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
