# Generated by Django 3.0.8 on 2020-08-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0046_remove_notification_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='href',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
