# Generated by Django 3.0.8 on 2020-08-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0048_auto_20200813_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorclassification',
            name='jury',
            field=models.CharField(choices=[('ENEM', 'ENEM'), ('CESPE', 'CESPE'), ('VUNESP', 'VUNESP')], default='ENEM', max_length=255),
        ),
        migrations.AddField(
            model_name='genericerrorclassification',
            name='jury',
            field=models.CharField(choices=[('ENEM', 'ENEM'), ('CESPE', 'CESPE'), ('VUNESP', 'VUNESP')], default='ENEM', max_length=255),
        ),
    ]
