# Generated by Django 3.0.8 on 2020-08-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0049_auto_20200814_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_level',
            field=models.CharField(blank=True, default='student', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='errorclassification',
            name='competency',
            field=models.CharField(choices=[('1', 'Competência 1'), ('2', 'Competência 2'), ('3', 'Competência 3'), ('4', 'Competência 4'), ('5', 'Competência 5'), ('a', 'Critério A'), ('b', 'Critério B'), ('c', 'Critério C'), ('0', 'Nota 0')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='errorclassification',
            name='jury',
            field=models.CharField(choices=[('ENEM', 'ENEM'), ('CESPE', 'CESPE'), ('VUNESP', 'VUNESP')], default='VUNESP', max_length=255),
        ),
        migrations.AlterField(
            model_name='genericerrorclassification',
            name='competency',
            field=models.CharField(choices=[('1', 'Competência 1'), ('2', 'Competência 2'), ('3', 'Competência 3'), ('4', 'Competência 4'), ('5', 'Competência 5'), ('a', 'Critério A'), ('b', 'Critério B'), ('c', 'Critério C'), ('0', 'Nota 0')], default='a', max_length=255),
        ),
        migrations.AlterField(
            model_name='genericerrorclassification',
            name='jury',
            field=models.CharField(choices=[('ENEM', 'ENEM'), ('CESPE', 'CESPE'), ('VUNESP', 'VUNESP')], default='VUNESP', max_length=255),
        ),
        migrations.AlterField(
            model_name='genericerrorclassification',
            name='target',
            field=models.CharField(default='formTextareaca', max_length=255),
        ),
    ]
