# Generated by Django 3.0.8 on 2020-08-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0050_auto_20200817_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='access_level',
        ),
    ]
