# Generated by Django 3.0.3 on 2020-08-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0052_mentoring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'notificação', 'verbose_name_plural': 'notificações'},
        ),
    ]
