# Generated by Django 3.0.10 on 2020-12-14 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0053_auto_20200826_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedexerciselist',
            name='essay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essay_manager.Essay'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genericerrorclassification',
            name='apply_on_select',
            field=models.BooleanField(default=True),
        ),
    ]
