# Generated by Django 3.0.10 on 2020-12-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0054_auto_20201214_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
