# Generated by Django 3.0.10 on 2020-12-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay_manager', '0055_exerciselist_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
