# Generated by Django 3.0.4 on 2020-06-23 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tps', '0002_auto_20200623_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='email',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tps',
            name='campus',
            field=models.CharField(choices=[('BSB', 'BRASÍLIA'), ('JUA', 'JUAZEIRO'), ('GOI', 'GOIANIA')], max_length=255, verbose_name='Campus'),
        ),
    ]
