# Generated by Django 3.0.4 on 2020-06-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0003_auto_20200623_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
