# Generated by Django 3.0.4 on 2020-06-23 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0004_auto_20200623_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tps',
            name='max_students',
        ),
        migrations.AddField(
            model_name='answer',
            name='tps',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tps.TPS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tps',
            name='max_answers',
            field=models.IntegerField(default=40, verbose_name='Número de respostas'),
        ),
    ]
