# Generated by Django 3.0.4 on 2020-06-23 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0005_auto_20200623_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='tps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tps.TPS'),
        ),
    ]
