# Generated by Django 3.0.4 on 2020-06-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0006_auto_20200623_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='tps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tps.TPS'),
        ),
    ]
