# Generated by Django 3.0.4 on 2020-06-24 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0007_auto_20200623_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
