# Generated by Django 3.0.4 on 2020-06-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0008_answer_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.CharField(default='Gabriel Lins', max_length=255),
            preserve_default=False,
        ),
    ]
