# Generated by Django 3.0.4 on 2020-06-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0009_answer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterModelOptions(
            name='tps',
            options={'verbose_name': 'Formulário', 'verbose_name_plural': 'Formulários'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='email',
        ),
    ]
