# Generated by Django 3.0.4 on 2020-06-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0010_auto_20200624_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps',
            name='max_questions',
            field=models.IntegerField(default=10, verbose_name='Número de questões'),
        ),
        migrations.AlterField(
            model_name='tps',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='tps',
            name='week',
            field=models.CharField(max_length=255, verbose_name='Semana'),
        ),
    ]
