# Generated by Django 3.0.4 on 2020-07-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0011_auto_20200630_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps',
            name='distractor',
            field=models.BooleanField(default=True, verbose_name='Produzir Distrator'),
        ),
        migrations.AddField(
            model_name='tps',
            name='score_z',
            field=models.BooleanField(default=True, verbose_name='Produzir Score Z'),
        ),
        migrations.AddField(
            model_name='tps',
            name='tbl',
            field=models.BooleanField(default=True, verbose_name='Produzir TBL'),
        ),
        migrations.AlterField(
            model_name='tps',
            name='end_date',
            field=models.DateTimeField(verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='tps',
            name='start_date',
            field=models.DateTimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='tps',
            name='week',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], max_length=255, verbose_name='Semana'),
        ),
    ]
