# Generated by Django 3.0.4 on 2020-07-01 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0012_auto_20200701_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tps',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='tps',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='tps',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='tps',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='tps',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='tps',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='tps',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='tps',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='tps',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='tps',
            name='q9',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=255)),
                ('tps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tps.TPS')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
    ]
