# Generated by Django 3.0.4 on 2020-07-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0013_auto_20200701_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
