# Generated by Django 3.0.4 on 2020-07-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0015_auto_20200702_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps',
            name='solutions',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
