# Generated by Django 3.0.4 on 2020-07-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0016_tps_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpsanswer',
            name='mailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tps',
            name='solutions',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Gabarito comentado'),
        ),
    ]
