# Generated by Django 3.0.4 on 2020-07-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0017_auto_20200703_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tps',
            name='distractor',
        ),
        migrations.AlterField(
            model_name='tps',
            name='score_z',
            field=models.BooleanField(default=True, verbose_name='Notificar Score Z'),
        ),
        migrations.AlterField(
            model_name='tps',
            name='tbl',
            field=models.BooleanField(default=True, verbose_name='Notificar TBL'),
        ),
    ]
