# Generated by Django 3.0.4 on 2020-07-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0018_auto_20200703_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tps',
            name='score_z',
        ),
        migrations.RemoveField(
            model_name='tps',
            name='tbl',
        ),
        migrations.AddField(
            model_name='tps',
            name='notify',
            field=models.BooleanField(default=True, verbose_name='Enviar ranking'),
        ),
    ]
