# Generated by Django 3.0.4 on 2020-07-23 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tps', '0019_auto_20200723_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPSSCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('tps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tps.TPS')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pontuação',
                'verbose_name_plural': 'Pontuações',
            },
        ),
    ]
