# Generated by Django 3.0.4 on 2020-07-23 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0020_tpsscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpsscore',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tpsscore',
            name='name',
        ),
        migrations.AddField(
            model_name='tpsscore',
            name='tps_answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tps.TPSAnswer'),
            preserve_default=False,
        ),
    ]
