# Generated by Django 3.0.4 on 2020-07-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0021_auto_20200723_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpsscore',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='tpsscore',
            name='tps',
        ),
        migrations.RemoveField(
            model_name='tpsscore',
            name='tps_answer',
        ),
        migrations.RemoveField(
            model_name='tpsscore',
            name='user',
        ),
        migrations.AddField(
            model_name='tpsscore',
            name='campus',
            field=models.CharField(choices=[('BSB', 'BRASÍLIA'), ('JUA', 'JUAZEIRO'), ('GOI', 'GOIANIA')], default='BSB', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tpsscore',
            name='email',
            field=models.CharField(max_length=255, default='gabriel.lins97@gmail.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tpsscore',
            name='month',
            field=models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Março'), ('4', 'Maio'), ('5', 'Abril'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tpsscore',
            name='group',
            field=models.CharField(choices=[('ENEM_ANUAL', 'ENEM ANUAL'), ('ENEM_SEMESTRAL', 'ENEM SEMESTRAL'), ('PARTICULARES', 'PARTICULARES')], max_length=255),
        ),
    ]
