# Generated by Django 3.0.4 on 2020-07-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0022_auto_20200726_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpsscore',
            name='campus',
            field=models.CharField(blank=True, choices=[('BSB', 'BRASÍLIA'), ('JUA', 'JUAZEIRO'), ('GOI', 'GOIANIA')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tpsscore',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tpsscore',
            name='group',
            field=models.CharField(blank=True, choices=[('ENEM_ANUAL', 'ENEM ANUAL'), ('ENEM_SEMESTRAL', 'ENEM SEMESTRAL'), ('PARTICULARES', 'PARTICULARES')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tpsscore',
            name='month',
            field=models.CharField(blank=True, choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Março'), ('4', 'Maio'), ('5', 'Abril'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=255, null=True),
        ),
    ]
