# Generated by Django 3.0.4 on 2020-07-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0023_auto_20200726_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps',
            name='group',
            field=models.CharField(blank=True, choices=[('ENEM_ANUAL', 'ENEM ANUAL'), ('ENEM_SEMESTRAL', 'ENEM SEMESTRAL'), ('PARTICULARES', 'PARTICULARES')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tps',
            name='questions',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Caderno de questões'),
        ),
    ]
