# Generated by Django 3.0.4 on 2020-07-28 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tps', '0024_auto_20200726_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='tps',
            name='group',
            field=models.CharField(blank=True, choices=[('ENEM_ANUAL', 'ENEM ANUAL'), ('ENEM_SEMESTRAL', 'ENEM SEMESTRAL'), ('PARTICULARES', 'PARTICULARES')], max_length=255, null=True, verbose_name='Grupo'),
        ),
    ]
