# Generated by Django 3.0.4 on 2020-07-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0025_auto_20200728_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpsscore',
            name='group',
        ),
        migrations.AddField(
            model_name='tpsanswer',
            name='accounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tpsanswer',
            name='grade_group',
            field=models.CharField(blank=True, choices=[('SCORE_Z', 'SCORE_Z'), ('TBL', 'TBL'), ('CBT', 'CBT')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tpsanswer',
            name='grade_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tpsanswer',
            name='top_student',
            field=models.BooleanField(default=False),
        ),
    ]
