# Generated by Django 3.0.4 on 2020-07-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0027_auto_20200728_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpsscore',
            name='group',
            field=models.CharField(blank=True, choices=[('ENEM_ANUAL', 'ENEM ANUAL'), ('ENEM_SEMESTRAL', 'ENEM SEMESTRAL'), ('PARTICULARES', 'PARTICULARES')], max_length=255, null=True),
        ),
    ]
