# Generated by Django 3.0.8 on 2020-08-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0029_auto_20200801_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpsanswer',
            name='mailed_answers',
            field=models.BooleanField(default=True),
        ),
    ]
