# Generated by Django 3.0.8 on 2020-08-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0031_auto_20200804_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpsanswer',
            name='mailed_answers',
            field=models.BooleanField(default=False),
        ),
    ]
