# Generated by Django 3.0.8 on 2020-08-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0032_auto_20200804_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps',
            name='mailed',
            field=models.BooleanField(default=False, verbose_name='Enviado ao professor'),
        ),
    ]
