# Generated by Django 3.0.8 on 2020-08-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0033_tps_mailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tps',
            name='mailed',
            field=models.BooleanField(default=True, verbose_name='Enviado ao professor'),
        ),
    ]
