# Generated by Django 3.0.3 on 2020-08-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0034_auto_20200805_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps',
            name='separate',
            field=models.BooleanField(default=True, verbose_name='Separar alunos em grupos'),
        ),
    ]
