# Generated by Django 3.0.8 on 2020-08-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0035_tps_separate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tps',
            name='week',
            field=models.CharField(choices=[('32', '32'), ('31', '31'), ('30', '30'), ('29', '29'), ('28', '28'), ('27', '27'), ('26', '26'), ('25', '25'), ('24', '24'), ('23', '23'), ('22', '22'), ('21', '21'), ('20', '20'), ('19', '19'), ('18', '18'), ('17', '17'), ('16', '16'), ('15', '15'), ('14', '14'), ('13', '13'), ('12', '12'), ('11', '11'), ('10', '10'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=255, verbose_name='Semana'),
        ),
    ]
