# Generated by Django 3.0.3 on 2020-08-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0037_tps__questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tps',
            old_name='_questions',
            new_name='original_questions',
        ),
    ]
