# Generated by Django 3.0.3 on 2020-08-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0038_auto_20200826_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tps',
            name='questions',
            field=models.FileField(default='', upload_to='uploads', verbose_name='Caderno de questões'),
            preserve_default=False,
        ),
    ]
