# Generated by Django 3.0.3 on 2020-08-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0039_auto_20200826_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps',
            name='mailed_files',
            field=models.BooleanField(default=False),
        ),
    ]
